module.exports = {
  aboutPageEditable: true,
  canShowCertificateAvailableDateField: false,
  courseDisplayName: 'Example course name',
  courseDisplayNameWithDefault: 'Example course name',
  creditEligibilityEnabled: true,
  enableExtendedCourseDetails: false,
  enrollmentEndEditable: true,
  isCreditCourse: false,
  isEntranceExamsEnabled: true,
  isPrerequisiteCoursesEnabled: true,
  languageOptions: [
    [
      'aa',
      'Afar',
    ],
  ],
  lmsLinkForAboutPage: 'http://localhost:18000/courses/course-v1:Edx+123+2023/about',
  licensingEnabled: true,
  marketingEnabled: false,
  mfeProctoredExamSettingsUrl: '',
  platformName: 'Your Platform Name Here',
  possiblePreRequisiteCourses: [
    {
      courseKey: 'course-v1:Test+123+2023',
      displayName: 'Test',
      lmsLink: '//localhost:18000/courses/course-v1:Test+123+2023/jump_to/block-v1:Test+123+2023+type@course+block@course',
      number: '123',
      org: 'Test',
      rerunLink: '/course_rerun/course-v1:Test+123+2023',
      run: '2023',
      url: '/course/course-v1:Test+123+2023',
    },
  ],
  shortDescriptionEditable: true,
  showMinGradeWarning: false,
  sidebarHtmlEnabled: false,
  upgradeDeadline: null,
  useV2CertDisplaySettings: false,
};
